channels:
- defaults
- conda-forge
dependencies:
- pip
- numpy
- scikit-learn
- pandas
- scipy
- elasticsearch
- matplotlib
- keras
- tensorflow
- theano
- pyodbc
- ipython
- statsmodels
- falcon
- flask
- nltk
- spacy
- pip:
  - ipykernel
